<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IsrDailyRetentionSubsidySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('isr_daily_retention_subsidies')->insert([
            [
                'lower_limit' => 0.01,
                'lower_limit_2' => 0.01,
                'upper_limit' => 21.20,
                'fixed_feed' => 0.00,
                'percentage_excess_to_lower_limit' => 1.92,
                'subsidy_for_employment' => 13.39,
                'year' => 2021,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'lower_limit' => 21.21,
                'lower_limit_2' => 21.21,
                'upper_limit' => 58.19,
                'fixed_feed' => 0.41,
                'percentage_excess_to_lower_limit' => 6.40,
                'subsidy_for_employment' => 13.39,
                'year' => 2021,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'lower_limit' => 21.21,
                'lower_limit_2' => 58.20,
                'upper_limit' => 87.28,
                'fixed_feed' => 0.41,
                'percentage_excess_to_lower_limit' => 6.40,
                'subsidy_for_employment' => 13.38,
                'year' => 2021,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'lower_limit' => 21.21,
                'lower_limit_2' => 87.29,
                'upper_limit' => 114.24,
                'fixed_feed' => 0.41,
                'percentage_excess_to_lower_limit' => 6.40,
                'subsidy_for_employment' => 13.38,
                'year' => 2021,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'lower_limit' => 21.21,
                'lower_limit_2' => 114.25,
                'upper_limit' => 116.38,
                'fixed_feed' => 0.41,
                'percentage_excess_to_lower_limit' => 6.40,
                'subsidy_for_employment' => 12.92,
                'year' => 2021,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'lower_limit' => 21.21,
                'lower_limit_2' => 116.39,
                'upper_limit' => 146.25,
                'fixed_feed' => 0.41,
                'percentage_excess_to_lower_limit' => 6.40,
                'subsidy_for_employment' => 12.58,
                'year' => 2021,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'lower_limit' => 21.21,
                'lower_limit_2' => 146.26,
                'upper_limit' => 155.17,
                'fixed_feed' => 0.41,
                'percentage_excess_to_lower_limit' => 6.40,
                'subsidy_for_employment' => 11.65,
                'year' => 2021,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'lower_limit' => 21.21,
                'lower_limit_2' => 155.18,
                'upper_limit' => 175.51,
                'fixed_feed' => 0.41,
                'percentage_excess_to_lower_limit' => 6.40,
                'subsidy_for_employment' => 10.69,
                'year' => 2021,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'lower_limit' => 21.21,
                'lower_limit_2' => 175.52,
                'upper_limit' => 179.96,
                'fixed_feed' => 0.41,
                'percentage_excess_to_lower_limit' => 6.40,
                'subsidy_for_employment' => 9.69,
                'year' => 2021,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'lower_limit' => 179.97,
                'lower_limit_2' => 179.97,
                'upper_limit' => 204.76,
                'fixed_feed' => 10.57,
                'percentage_excess_to_lower_limit' => 10.88,
                'subsidy_for_employment' => 9.69,
                'year' => 2021,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'lower_limit' => 179.97,
                'lower_limit_2' => 204.77,
                'upper_limit' => 234.01,
                'fixed_feed' => 10.57,
                'percentage_excess_to_lower_limit' => 10.88,
                'subsidy_for_employment' => 8.34,
                'year' => 2021,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'lower_limit' => 179.97,
                'lower_limit_2' => 234.02,
                'upper_limit' => 242.84,
                'fixed_feed' => 10.57,
                'percentage_excess_to_lower_limit' => 10.88,
                'subsidy_for_employment' => 7.16,
                'year' => 2021,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'lower_limit' => 179.97,
                'lower_limit_2' => 242.85,
                'upper_limit' => 316.27,
                'fixed_feed' => 10.57,
                'percentage_excess_to_lower_limit' => 10.88,
                'subsidy_for_employment' => 0.00,
                'year' => 2021,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'lower_limit' => 316.28,
                'lower_limit_2' => 316.28,
                'upper_limit' => 367.65,
                'fixed_feed' => 25.40,
                'percentage_excess_to_lower_limit' => 16.00,
                'subsidy_for_employment' => 0.00,
                'year' => 2021,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'lower_limit' => 367.66,
                'lower_limit_2' => 367.66,
                'upper_limit' => 440.18,
                'fixed_feed' => 33.62,
                'percentage_excess_to_lower_limit' => 17.92,
                'subsidy_for_employment' => 0.00,
                'year' => 2021,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'lower_limit' => 440.19,
                'lower_limit_2' => 440.19,
                'upper_limit' => 887.78,
                'fixed_feed' => 46.62,
                'percentage_excess_to_lower_limit' => 21.36,
                'subsidy_for_employment' => 0.00,
                'year' => 2021,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'lower_limit' => 887.79,
                'lower_limit_2' => 887.79,
                'upper_limit' => 1399.26,
                'fixed_feed' => 142.22,
                'percentage_excess_to_lower_limit' => 23.52,
                'subsidy_for_employment' => 0.00,
                'year' => 2021,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'lower_limit' => 1399.27,
                'lower_limit_2' => 1399.27,
                'upper_limit' => 2671.42,
                'fixed_feed' => 262.52,
                'percentage_excess_to_lower_limit' => 30.00,
                'subsidy_for_employment' => 0.00,
                'year' => 2021,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'lower_limit' => 2671.43,
                'lower_limit_2' => 2671.43,
                'upper_limit' => 3561.90,
                'fixed_feed' => 644.17,
                'percentage_excess_to_lower_limit' => 32.00,
                'subsidy_for_employment' => 0.00,
                'year' => 2021,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'lower_limit' => 3561.91,
                'lower_limit_2' => 3561.91,
                'upper_limit' => 10685.69,
                'fixed_feed' => 929.12,
                'percentage_excess_to_lower_limit' => 34.00,
                'subsidy_for_employment' => 0.00,
                'year' => 2021,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'lower_limit' => 10685.70,
                'lower_limit_2' => 10685.70,
                'upper_limit' => 999999,
                'fixed_feed' => 3351.21,
                'percentage_excess_to_lower_limit' => 35.00,
                'subsidy_for_employment' => 0.00,
                'year' => 2021,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
        ]);
    }
}
